// AUTO-GENERATED by scripts/generate-oauth-config.cjs — do not edit or commit.
export const GOOGLE_WEB_CLIENT_ID = "175738189642-d5g8fk7l69pii8pndo5rh602itfik93a.apps.googleusercontent.com";
export const GOOGLE_ANDROID_CLIENT_ID = "480194292084-rs25996r6etd0klq469q5c4mk2pvevua.apps.googleusercontent.com";
export const GOOGLE_IOS_CLIENT_ID = "";
